from django.db import models

# Create your models here.

class CV(models.Model):
    # Unique ID will automatically be generated by Django, but you can specify it if needed
    id = models.AutoField(primary_key=True)  # Automatically increments to create a unique ID
    
    name = models.CharField(max_length=100)  # The name of the person
    surname = models.CharField(max_length=100)  # The surname of the person
    email = models.EmailField(unique=True)  # Ensures email is unique
    phone = models.CharField(max_length=15)  # The phone number, adjust the length if needed
    photo = models.ImageField(upload_to='cv_photos/', null=True, blank=True)  # Optional photo
    localization = models.CharField(max_length=255)  # The location, can be a city or region
    summary = models.TextField()  # A short summary or bio
    job_opportunity = models.TextField()  # Potential job opportunities or goals

    def __str__(self):
        return f'{self.name} {self.surname}'

    class Meta:
        verbose_name = 'CV'
        verbose_name_plural = 'CVs'