from django.db import models

from django.contrib import admin

# Create your models here.

class CV(models.Model):
    # Unique ID will automatically be generated by Django, but you can specify it if needed
    id = models.AutoField(primary_key=True)  # Automatically increments to create a unique ID
    
    name = models.CharField(max_length=100)  # The name of the person
    surname = models.CharField(max_length=100)  # The surname of the person
    email = models.EmailField(unique=True)  # Ensures email is unique
    phone = models.CharField(max_length=15)  # The phone number, adjust the length if needed
    photo = models.ImageField(upload_to='cv_photos/', null=True, blank=True)  # Optional photo
    localization = models.CharField(max_length=255)  # The location, can be a city or region
    summary = models.TextField()  # A short summary or bio
    job_opportunity = models.TextField()  # Potential job opportunities or goals

    def __str__(self):
        return f'{self.name} {self.surname}'

    class Meta:
        verbose_name = 'CV'
        verbose_name_plural = 'CVs'

class CVAdmin(admin.ModelAdmin):
    # List the fields to display in the list view of the admin interface
    list_display = ('name', 'surname', 'email', 'phone', 'localization', 'summary', 'job_opportunity', 'photo')

    # Add search functionality by name or email
    search_fields = ('name', 'surname', 'email')

    # Add filters to make it easier to filter CVs by certain fields
    list_filter = ('localization',)

    # Add options for fieldsets (grouping fields in the form view)
    fieldsets = (
        (None, {
            'fields': ('name', 'surname', 'email', 'phone', 'localization', 'summary', 'job_opportunity')
        }),
        ('Photo', {
            'fields': ('photo',),
            'classes': ('collapse',)  # Allows collapsing the photo fieldset
        })
    )

    # You can specify form layouts or add extra functionality as needed
    # Exclude or customize certain fields in the admin form, if necessary
    exclude = ['photo']  # For example, if you don't want the photo field to be editable here

    # Optional: Customize the list view ordering
    ordering = ['name', 'surname']